# -*- coding: utf-8 -*-
"""Movie Recommendation .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRlvygGHPQ61HGES8TQPfB-rIwwDSIkp
"""

pip install kaggle

# Define the dataset slug (from the Kaggle URL)
dataset_slug = 'handekln/movielens-20m-dataset'

# Define the destination directory
destination_dir = 'DATA'

# Create the destination directory if it doesn't exist
import os
if not os.path.exists(destination_dir):
    os.makedirs(destination_dir)

# Download and unzip the dataset using Kaggle CLI
# The -p flag specifies the path where to download the dataset
# The --unzip flag extracts the content of the zip file after downloading
!kaggle datasets download -d {dataset_slug} -p {destination_dir} --unzip

print(f"Dataset downloaded and unzipped to '{destination_dir}/'")

"""ratings.csv userId | movieId | rating | timestamp

movies.csv movieId | title | genres

tags.csv userId | movieId | tag | timestamp

links.csv movieId | imdbId | tmdbId

genome_scores.csv movieId | tagId | relevance

genome_tags.csv tagId | tag



User → rates movie → ratings.csv

Movie → has info → movies.csv

Movie → has meaning → tags / genome

Movie → links external → links.csv
"""

import pandas as pd

movies = pd.read_csv('/content/DATA/archive/movie.csv')
ratings = pd.read_csv('/content/DATA/archive/rating.csv')

movies.head()

ratings.head()

movies.info()

ratings.info()

movies['genres'].value_counts()

print("=== RATINGS ===")
print(f"Total ratings:    {len(ratings):,}")
print(f"Unique users:     {ratings['userId'].nunique():,}")
print(f"Unique movies:    {ratings['movieId'].nunique():,}")
print(f"Rating scale:     {ratings['rating'].min()} – {ratings['rating'].max()}")
print(f"Average rating:   {ratings['rating'].mean():.2f}")

# How many movies has the average user rated?
ratings_per_user = ratings.groupby('userId')['movieId'].count()
print(f"\nRatings per user:")
print(f"  min:    {ratings_per_user.min()}")
print(f"  median: {ratings_per_user.median():.0f}")
print(f"  max:    {ratings_per_user.max()}")

# How many ratings does the average movie have?
ratings_per_movie = ratings.groupby('movieId')['rating'].count()
print(f"\nRatings per movie:")
print(f"  min:    {ratings_per_movie.min()}")
print(f"  median: {ratings_per_movie.median():.0f}")
print(f"  max:    {ratings_per_movie.max()}")

(movies['genres'] =='').sum()

(movies['genres'] =='no genres listed').sum()

#Missing values
movies.isnull().sum()

#Duplicates
movies.duplicated().sum()

#visualution
ratings['rating'].value_counts().plot(kind='bar')
#

movies['genres'] = movies['genres'].fillna('')

movies = movies.drop_duplicates()

l = set()
# Iterate over each row's genres, split them, and add to the set
for genre_list in movies['genres'].str.split('|'):
    for genre in genre_list:
        if genre and genre != '(no genres listed)': # Ensure valid genre and not the placeholder
            l.add(genre)
print(l)

print (len(l))

#vectoration
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['genres'])

from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

indices = pd.Series(movies.index, index=movies['title']).drop_duplicates()

def recommend(movie_title, top_k=5):
  idx = indices[movie_title]
  sim_scores = list(enumerate(cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  sim_scores = sim_scores[1:top_k+1]
  movie_indices = [i[0] for i in sim_scores]
  return movies['title'].iloc[movie_indices]

print("── Recommendations for Toy Story (1995) ──")
print(recommend('Toy Story (1995)', 5))

movies[movies['title'].str.contains("Star Wars", case=False, na=False)]['title']

print(recommend('Star Wars: Episode IV - A New Hope (1977)', 5))

print("\n── Recommendations for Fargo (1996) ──")
recommend('Fargo (1996)', 5)

def Recommendations(movie_title, top_k=5):
    matches = movies[movies['title'].str.contains(movie_title, case=False, na=False,regex=False)]

    if matches.empty:
        return "Movie not found."

    exact_title = matches.iloc[0]['title']
    idx = indices[exact_title]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_k+1]

    movie_indices = [i[0] for i in sim_scores]
    return movies['title'].iloc[movie_indices]

print("\n── Recommendations for Star Wars (1977) ──")
print( Recommendations('Star Wars (1977)', 5))

print(Recommendations("Star Wars (1977)", 5))

print(Recommendations("Star Wars", 5))

Recommendations('Fargo', 5)

import joblib

joblib.dump((movies, cosine_sim, indices), "movie_recommender.joblib")